### ISSUE TITLE
宿主app点击 “点击”按钮奔溃

### ISSUE THREAD

**Issue by 2022happynew** [colinNaive/PluginApplication#3]
`    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ctrip.pluginapplication/com.ctrip.pluginapplication.ProxyActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2193)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.ctrip.pluginapplication.ProxyActivity.onStart(ProxyActivity.java:66)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
        at android.app.Activity.performStart(Activity.java:5241)`

**Comment by SZooo** [comment]
还有“加载”按钮，点击也是崩溃

**Comment by sanyusily** [comment]
加载崩溃是没有把apk放入 根目录

**Comment by sanyusily** [comment]
Unable to start activity ComponentInfo{com.ctrip.pluginapplication/com.ctrip.pluginapplication.ProxyActivity}: java.lang.ClassCastException: com.ctrip.pluginapplication.MainActivity cannot be cast to com.ctrip.standard.AppInterface

appInterface = (AppInterface) instance; 代码转换崩溃了
at com.ctrip.pluginapplication.ProxyActivity.onCreate(ProxyActivity.java:46)
